# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bwvdyLHpJSvkdQAlFUisj0q80l2WViX
"""

################################
# Author: Hui Fang
# Purpose: ST 554 Final Project
# Date: 4/23/2026
################################

import pandas as pd
import time
import os

# Create the stream input directory if it doesn't exist
if not os.path.exists('stream_input'):
    os.makedirs('stream_input')

df = pd.read_csv("/content/power_streaming_data.csv")
# check if the data read in correctly
df.head(10)

# randomly sample and write 20 csv files
for i in range(20):
    sample = df.sample(n = 5)
    sample.to_csv(f"stream_input/sample_{i}.csv", index = False)
    time.sleep(10) # pause 10 seconds between outputs

