# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bwvdyLHpJSvkdQAlFUisj0q80l2WViX
"""

################################
# Author: Hui Fang
# Purpose: ST 554 Final Project
# Date: 4/23/2026
################################

import pandas as pd
import time
import os

# 1. Ensure the input directory exists
input_dir = '/content/stream_input'
if not os.path.exists(input_dir):
    os.makedirs(input_dir)

# 2. Clear existing files in the stream_input directory
for f in os.listdir(input_dir):
    os.remove(os.path.join(input_dir, f))

# 3. Load the full streaming dataset
df = pd.read_csv("https://www4.stat.ncsu.edu/~online/datasets/power_streaming_data.csv")

# 4. wait for Spark to start watching
time.sleep(10)

# 5. randomly sample new files
for i in range(10):
    sample = df.sample(n = 5)                                             # sample 5 rows
    sample.to_csv(f"/content/stream_input/sample_{i}.csv", index = False) # write the sample file to input folder
    time.sleep(10)                                                        # pause 10 seconds between outputs

print("Starting data generation...")

